# Generated by Django 5.0.1 on 2024-01-27 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='test@yahoo.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(default='test@yahoo.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='email',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShelterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiy_requested', models.IntegerField()),
                ('fufilled', models.BooleanField(default=False)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shelter')),
                ('tickets', models.ManyToManyField(to='api.ticket')),
            ],
        ),
    ]
