# Generated by Django 5.0.1 on 2024-01-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_restaurant_email_restaurant_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterrequest',
            name='food_category',
            field=models.IntegerField(choices=[(0, 'Meats'), (1, 'Vegetables'), (2, 'Non-Perishables')], default=0),
        ),
    ]
