# Generated by Django 5.0.1 on 2024-01-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shelterrequest_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelterrequest',
            old_name='fufilled',
            new_name='fulfilled',
        ),
    ]
