# Generated by Django 5.0.1 on 2024-02-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shelterrequest_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterrequest',
            name='food_category',
            field=models.IntegerField(choices=[(0, 'Canned Foods'), (1, 'Vegetables'), (2, 'Non-Perishables')], default=0),
        ),
        migrations.AlterField(
            model_name='shelterrequest',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='api.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='food_category',
            field=models.IntegerField(choices=[(0, 'Canned Foods'), (1, 'Vegetables'), (2, 'Non-Perishables')], default=0),
        ),
    ]
