# Generated by Django 5.0.1 on 2024-02-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_organizer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodinspector',
            options={'permissions': [('inspector', 'Food Inspector')]},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'permissions': [('organizer', 'Organizer')]},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'permissions': [('volunteer', 'Volunteer')]},
        ),
    ]
