# Generated by Django 5.0.1 on 2024-02-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_foodinspector_options_alter_organizer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'permissions': (('organizer', 'Organizer'),)},
        ),
    ]
