# Generated by Django 5.0.1 on 2024-02-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_organizer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodinspector',
            options={'permissions': (('inspector', 'Food Inspector'),)},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'permissions': (('restaurant', 'Restaurant'),)},
        ),
        migrations.AlterModelOptions(
            name='shelter',
            options={'permissions': (('shelter', 'Shelter'),)},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'permissions': (('volunteer', 'Volunteer'),)},
        ),
    ]
