# Generated by Django 5.0.1 on 2024-02-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_foodinspector_options_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'permissions': (('manage_restaurant', 'Can manage restaurant'),)},
        ),
    ]
