# Generated by Django 5.0.1 on 2024-02-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'permissions': (('restaurant', 'Can manage restaurant'),)},
        ),
    ]
